Class java.text.AttributedCharacterIterator.Attribute Extends java.io.Serializable [ ProcedureBlock ]
{

Parameter IMPORTTIMESTAMP As STRING = "2019-01-14 21:02:00.0";

Method hashCode() As %ObjectHandle
{
	Quit ..%IR("hashCode")
}

///p0: class java.lang.Object
Method equals(ByRef p0 As %ObjectHandle) As %ObjectHandle
{
	Quit ..%IR("equals",.p0)
}

Method toString() As %ObjectHandle
{
	Quit ..%IR("toString")
}

Parameter LANGUAGE As STRING = "java.text.AttributedCharacterIterator$Attribute(language)";

Parameter READING As STRING = "java.text.AttributedCharacterIterator$Attribute(reading)";

Parameter INPUTuMETHODuSEGMENT As STRING = "java.text.AttributedCharacterIterator$Attribute(input_method_segment)";

}
