Class com.intersystems.jdbc.BufferRO Extends com.intersystems.jdbc.ListReader [ ProcedureBlock ]
{

Parameter IMPORTTIMESTAMP As STRING = "2019-03-13 12:37:46.0";

Method getHeaderCount() As %ObjectHandle
{
	Quit ..%IR("getHeaderCount")
}

///p0: class java.lang.String
Method GetParameter(ByRef p0 As %ObjectHandle) As %ObjectHandle
{
	Quit ..%IR("GetParameter",.p0)
}

Method getID() As %ObjectHandle
{
	Quit ..%IR("getID")
}

Method readServerEncoding() As %ObjectHandle
{
	Quit ..%IR("readServerEncoding")
}

}
