Class java.security.Key Extends java.io.Serializable [ ProcedureBlock ]
{

Parameter IMPORTTIMESTAMP As STRING = "2019-01-14 21:02:00.0";

Method getEncoded() As %ObjectHandle
{
	Quit ..%IR("getEncoded")
}

Method getAlgorithm() As %ObjectHandle
{
	Quit ..%IR("getAlgorithm")
}

Method getFormat() As %ObjectHandle
{
	Quit ..%IR("getFormat")
}

Parameter serialVersionUID As STRING = 6603384152749567654;

}
