Class java.lang.reflect.Executable Extends (java.lang.reflect.AccessibleObject, java.lang.reflect.Member, java.lang.reflect.GenericDeclaration) [ Inheritance = right, ProcedureBlock ]
{

Parameter IMPORTTIMESTAMP As STRING = "2019-01-14 21:02:00.0";

Method getName() As %ObjectHandle
{
	Quit ..%IR("getName")
}

Method getParameterCount() As %ObjectHandle
{
	Quit ..%IR("getParameterCount")
}

Method isVarArgs() As %ObjectHandle
{
	Quit ..%IR("isVarArgs")
}

Method isSynthetic() As %ObjectHandle
{
	Quit ..%IR("isSynthetic")
}

Method getParameterTypes() As %ObjectHandle
{
	Quit ..%IR("getParameterTypes")
}

Method getAnnotatedParameterTypes() As %ObjectHandle
{
	Quit ..%IR("getAnnotatedParameterTypes")
}

Method getGenericExceptionTypes() As %ObjectHandle
{
	Quit ..%IR("getGenericExceptionTypes")
}

Method getAnnotatedReceiverType() As %ObjectHandle
{
	Quit ..%IR("getAnnotatedReceiverType")
}

Method getDeclaredAnnotations() As %ObjectHandle
{
	Quit ..%IR("getDeclaredAnnotations")
}

Method getAnnotatedExceptionTypes() As %ObjectHandle
{
	Quit ..%IR("getAnnotatedExceptionTypes")
}

Method getDeclaringClass() As %ObjectHandle
{
	Quit ..%IR("getDeclaringClass")
}

Method getExceptionTypes() As %ObjectHandle
{
	Quit ..%IR("getExceptionTypes")
}

Method getGenericParameterTypes() As %ObjectHandle
{
	Quit ..%IR("getGenericParameterTypes")
}

///p0: class java.lang.Class
Method getAnnotationsByType(ByRef p0 As %ObjectHandle) As %ObjectHandle
{
	Quit ..%IR("getAnnotationsByType",.p0)
}

///p0: class java.lang.Class
Method getAnnotation(ByRef p0 As %ObjectHandle) As %ObjectHandle
{
	Quit ..%IR("getAnnotation",.p0)
}

Method toGenericString() As %ObjectHandle
{
	Quit ..%IR("toGenericString")
}

Method getParameters() As %ObjectHandle
{
	Quit ..%IR("getParameters")
}

Method getModifiers() As %ObjectHandle
{
	Quit ..%IR("getModifiers")
}

Method getTypeParameters() As %ObjectHandle
{
	Quit ..%IR("getTypeParameters")
}

Method getParameterAnnotations() As %ObjectHandle
{
	Quit ..%IR("getParameterAnnotations")
}

Method getAnnotatedReturnType() As %ObjectHandle
{
	Quit ..%IR("getAnnotatedReturnType")
}

}
