Class java.lang.reflect.Field Extends (java.lang.reflect.AccessibleObject, java.lang.reflect.Member) [ Inheritance = right, ProcedureBlock ]
{

Parameter IMPORTTIMESTAMP As STRING = "2019-01-14 21:02:00.0";

///p0: class java.lang.Object
///p1: byte
Method setByte(ByRef p0 As %ObjectHandle, ByRef p1 As %ObjectHandle)
{
	Do ..%I("setByte",.p0,.p1)
}

///p0: class java.lang.Object
Method getByte(ByRef p0 As %ObjectHandle) As %ObjectHandle
{
	Quit ..%IR("getByte",.p0)
}

Method getName() As %ObjectHandle
{
	Quit ..%IR("getName")
}

///p0: class java.lang.Object
Method getDouble(ByRef p0 As %ObjectHandle) As %ObjectHandle
{
	Quit ..%IR("getDouble",.p0)
}

Method isSynthetic() As %ObjectHandle
{
	Quit ..%IR("isSynthetic")
}

///p0: class java.lang.Object
Method getFloat(ByRef p0 As %ObjectHandle) As %ObjectHandle
{
	Quit ..%IR("getFloat",.p0)
}

///p0: class java.lang.Object
///p1: short
Method setShort(ByRef p0 As %ObjectHandle, ByRef p1 As %ObjectHandle)
{
	Do ..%I("setShort",.p0,.p1)
}

Method getDeclaredAnnotations() As %ObjectHandle
{
	Quit ..%IR("getDeclaredAnnotations")
}

///p0: class java.lang.Object
///p1: char
Method setChar(ByRef p0 As %ObjectHandle, ByRef p1 As %ObjectHandle)
{
	Do ..%I("setChar",.p0,.p1)
}

///p0: class java.lang.Object
///p1: double
Method setDouble(ByRef p0 As %ObjectHandle, ByRef p1 As %ObjectHandle)
{
	Do ..%I("setDouble",.p0,.p1)
}

Method getDeclaringClass() As %ObjectHandle
{
	Quit ..%IR("getDeclaringClass")
}

///p0: class java.lang.Class
Method getAnnotationsByType(ByRef p0 As %ObjectHandle) As %ObjectHandle
{
	Quit ..%IR("getAnnotationsByType",.p0)
}

Method hashCode() As %ObjectHandle
{
	Quit ..%IR("hashCode")
}

///p0: class java.lang.Object
Method get(ByRef p0 As %ObjectHandle) As %ObjectHandle
{
	Quit ..%IR("get",.p0)
}

Method toGenericString() As %ObjectHandle
{
	Quit ..%IR("toGenericString")
}

///p0: class java.lang.Object
Method getBoolean(ByRef p0 As %ObjectHandle) As %ObjectHandle
{
	Quit ..%IR("getBoolean",.p0)
}

Method getModifiers() As %ObjectHandle
{
	Quit ..%IR("getModifiers")
}

Method getGenericType() As %ObjectHandle
{
	Quit ..%IR("getGenericType")
}

Method getAnnotatedType() As %ObjectHandle
{
	Quit ..%IR("getAnnotatedType")
}

///p0: class java.lang.Object
///p1: float
Method setFloat(ByRef p0 As %ObjectHandle, ByRef p1 As %ObjectHandle)
{
	Do ..%I("setFloat",.p0,.p1)
}

///p0: class java.lang.Object
///p1: class java.lang.Object
Method set(ByRef p0 As %ObjectHandle, ByRef p1 As %ObjectHandle)
{
	Do ..%I("set",.p0,.p1)
}

///p0: class java.lang.Object
Method getShort(ByRef p0 As %ObjectHandle) As %ObjectHandle
{
	Quit ..%IR("getShort",.p0)
}

///p0: class java.lang.Object
///p1: int
Method setInt(ByRef p0 As %ObjectHandle, ByRef p1 As %ObjectHandle)
{
	Do ..%I("setInt",.p0,.p1)
}

///p0: class java.lang.Object
Method getLong(ByRef p0 As %ObjectHandle) As %ObjectHandle
{
	Quit ..%IR("getLong",.p0)
}

///p0: class java.lang.Object
Method getChar(ByRef p0 As %ObjectHandle) As %ObjectHandle
{
	Quit ..%IR("getChar",.p0)
}

///p0: class java.lang.Object
Method getInt(ByRef p0 As %ObjectHandle) As %ObjectHandle
{
	Quit ..%IR("getInt",.p0)
}

///p0: class java.lang.Object
///p1: long
Method setLong(ByRef p0 As %ObjectHandle, ByRef p1 As %ObjectHandle)
{
	Do ..%I("setLong",.p0,.p1)
}

///p0: class java.lang.Class
Method getAnnotation(ByRef p0 As %ObjectHandle) As %ObjectHandle
{
	Quit ..%IR("getAnnotation",.p0)
}

Method getType() As %ObjectHandle
{
	Quit ..%IR("getType")
}

///p0: class java.lang.Object
Method equals(ByRef p0 As %ObjectHandle) As %ObjectHandle
{
	Quit ..%IR("equals",.p0)
}

Method toString() As %ObjectHandle
{
	Quit ..%IR("toString")
}

Method isEnumConstant() As %ObjectHandle
{
	Quit ..%IR("isEnumConstant")
}

///p0: class java.lang.Object
///p1: boolean
Method setBoolean(ByRef p0 As %ObjectHandle, ByRef p1 As %ObjectHandle)
{
	Do ..%I("setBoolean",.p0,.p1)
}

}
