Class java.lang.reflect.Member Extends %Net.Remote.Proxy [ ProcedureBlock ]
{

Parameter IMPORTTIMESTAMP As STRING = "2019-01-14 21:02:00.0";

Method getDeclaringClass() As %ObjectHandle
{
	Quit ..%IR("getDeclaringClass")
}

Method getName() As %ObjectHandle
{
	Quit ..%IR("getName")
}

Method isSynthetic() As %ObjectHandle
{
	Quit ..%IR("isSynthetic")
}

Method getModifiers() As %ObjectHandle
{
	Quit ..%IR("getModifiers")
}

Parameter PUBLIC As INTEGER = 0;

Parameter DECLARED As INTEGER = 1;

}
