Class java.lang.reflect.TypeVariable Extends (java.lang.reflect.Type, java.lang.reflect.AnnotatedElement) [ Inheritance = right, ProcedureBlock ]
{

Parameter IMPORTTIMESTAMP As STRING = "2019-01-14 21:02:00.0";

Method getAnnotatedBounds() As %ObjectHandle
{
	Quit ..%IR("getAnnotatedBounds")
}

Method getName() As %ObjectHandle
{
	Quit ..%IR("getName")
}

Method getBounds() As %ObjectHandle
{
	Quit ..%IR("getBounds")
}

Method getGenericDeclaration() As %ObjectHandle
{
	Quit ..%IR("getGenericDeclaration")
}

}
